apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment-jenkins
  namespace: jenkins-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: daisy715/portfolio-project:latest
          ports:
            - containerPort: 3000
