apiVersion: v1
kind: Service
metadata: 
  name: portfolio-service-jenkins
spec:
  selector:
    app: portfolio
  type: NodePort
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30050
